<a href="https://colab.research.google.com/github/antonum/Redis-Workshops/blob/experimental/ipywidgets.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import ipywidgets as widgets

In [ ]:
data = {
    "number": 10,
    "category": "FOOD"
}

In [ ]:
slider1 = widgets.IntSlider(value=data["number"], max=1000, min=0, description="Number")
display(slider1)
category1=widgets.Select(
    options=['FOOD', 'BEVERAGES', 'SNACKS'],
    value=data["category"],
    rows=1,
    description='OS:',
    disabled=False
)
display(category1)

IntSlider(value=10, description='Number', max=1000)

Select(description='OS:', index=1, options=('FOOD', 'BEVERAGES', 'SNACKS'), rows=1, value='BEVERAGES')

In [ ]:
data["number"]=slider1.value
data["category"]=category1.value
data

{'number': 427, 'category': 'BEVERAGES'}

In [ ]:
from ipywidgets import Button, Layout, jslink, IntText, IntSlider
widgets.Button(description="Loan Approved", button_style='success', layout=Layout(height='auto', width='auto'))

Button(button_style='success', description='Loan Approved', layout=Layout(height='auto', width='auto'), style=…

In [37]:
import pandas as pd
import ipywidgets as widgets
from IPython.display import display

# Sample DataFrames
df1 = pd.DataFrame({'col1': [1, 2, 3], 'col2': [4, 5, 6]})
df2 = pd.DataFrame({'col3': [7, 8, 9], 'col4': [10, 11, 12]})
df3 = pd.DataFrame({'col5': [13, 14, 15], 'col6': [16, 17, 18]})

# Create output widgets for each DataFrame
out1 = widgets.Output()
out2 = widgets.Output()
out3 = widgets.Output()

# Display DataFrames in the output widgets
with out1:
    print("Original")
    display(df1)
with out2:
    display(df2)
with out3:
    display(df3)

# Arrange output widgets in columns using HBox
widgets.HBox([out1, out2, out3])

HBox(children=(Output(), Output(), Output()))