<a href="https://colab.research.google.com/github/antonum/Redis-Workshops/blob/experimental/Kaggle_Sparkov.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
transactions = pd.read_csv('fraudTrain.csv')
transactions.head()

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,2019-01-01 00:00:18,2703186189652095,"fraud_Rippin, Kub and Mann",misc_net,4.97,Jennifer,Banks,F,561 Perry Cove,...,36.0788,-81.1781,3495.0,"Psychologist, counselling",1988-03-09,0b242abb623afc578575680df30655b9,1.325376e+09,36.011293,-82.048315,0.0
1,1,2019-01-01 00:00:44,630423337322,"fraud_Heller, Gutmann and Zieme",grocery_pos,107.23,Stephanie,Gill,F,43039 Riley Greens Suite 393,...,48.8878,-118.2105,149.0,Special educational needs teacher,1978-06-21,1f76529f8574734946361c461b024d99,1.325376e+09,49.159047,-118.186462,0.0
2,2,2019-01-01 00:00:51,38859492057661,fraud_Lind-Buckridge,entertainment,220.11,Edward,Sanchez,M,594 White Dale Suite 530,...,42.1808,-112.2620,4154.0,Nature conservation officer,1962-01-19,a1a22d70485983eac12b5b88dad1cf95,1.325376e+09,43.150704,-112.154481,0.0
3,3,2019-01-01 00:01:16,3534093764340240,"fraud_Kutch, Hermiston and Farrell",gas_transport,45.00,Jeremy,White,M,9443 Cynthia Court Apt. 038,...,46.2306,-112.1138,1939.0,Patent attorney,1967-01-12,6b849c168bdad6f867558c3793159a81,1.325376e+09,47.034331,-112.561071,0.0
4,4,2019-01-01 00:03:06,375534208663984,fraud_Keeling-Crist,misc_pos,41.96,Tyler,Garcia,M,408 Bradley Rest,...,38.4207,-79.4629,99.0,Dance movement psychotherapist,1986-03-28,a41d7549acf90789359a9aa5346dcb46,1.325376e+09,38.674999,-78.632459,0.0

In [2]:
from sklearn.linear_model import LinearRegression, LogisticRegression
# import the Decision Tree Classifier Model from scikit-learn
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import LinearSVC

In [14]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
for column in transactions.columns:
       if transactions[column].dtype == type(object):
           transactions[column] = le.fit_transform(transactions[column])
transactions.dropna(inplace=True)
transactions

,Unnamed: 0,trans_date_trans_time,cc_num,merchant,category,amt,first,last,gender,street,...,lat,long,city_pop,job,dob,trans_num,unix_time,merch_lat,merch_long,is_fraud
0,0,0,2703186189652095,514,9,4.97,160,18,0,556,...,36.0788,-81.1781,3495.0,370,762,45237,1.325376e+09,36.011293,-82.048315,0.0
1,1,1,630423337322,241,5,107.23,305,157,0,425,...,48.8878,-118.2105,149.0,427,590,127581,1.325376e+09,49.159047,-118.186462,0.0
2,2,2,38859492057661,390,1,220.11,113,380,1,590,...,42.1808,-112.2620,4154.0,307,291,655604,1.325376e+09,43.150704,-112.154481,0.0
3,3,3,3534093764340240,360,3,45.00,161,461,1,911,...,46.2306,-112.1138,1939.0,328,382,435969,1.325376e+09,47.034331,-112.561071,0.0
4,4,4,375534208663984,297,10,41.96,331,149,1,410,...,38.4207,-79.4629,99.0,116,717,665481,1.325376e+09,38.674999,-78.632459,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1038246,1038246,1020473,4099707841315751,214,10,1.22,150,409,1,102,...,38.2586,-78.4074,9815.0,121,542,731387,1.362595e+09,37.298391,-78.227014,0.0
1038247,1038247,1020474,3513618443244549,16,2,52.60,11,337,0,924,...,43.7588,-97.8712,355.0,194,191,727984,1.362595e+09,42.828576,-96.962369,0.0
1038248,1038248,1020475,4048508450704760,53,13,9.78,67,282,0,499,...,41.3660,-98.0054,1749.0,440,504,1033751,1.362595e+09,41.837069,-98.390748,0.0
1038249,1038249,1020476,4265776278887457,579,6,34.01,72,30,0,668,...,35.2087,-92.2123,969.0,337,172,715523,1.362595e+09,35.486998,-92.691084,0.0
1038250,1038250,1020477,4666314527820883145,506,7,78.35,136,422,1,574,...,41.0233,-98.9041,2202.0,426,524,463934,1.362595e+09,40.800635,-99.249373,0.0

In [15]:
X=transactions.drop(columns=['is_fraud','trans_date_trans_time'])
y=transactions['is_fraud']
model = DecisionTreeClassifier()
model.fit(X, y)

DecisionTreeClassifier()

NotFittedError: This LabelEncoder instance is not fitted yet. Call 'fit' with appropriate arguments before using this estimator.